[package]
name = "slotted-rise"
version = "0.1.0"
edition = "2021"

[dependencies]
slotted-egraphs = "=0.0.15"
symbol_table = { version = "0.3", features = ["global"]}
memory-stats = "1.0.0"

[profile.release]
debug = true
